use mock npm/ynpm, clean up tests

diff --git a/tests/fixtures/mockbin/npm-fail/npm b/tests/fixtures/mockbin/npm-fail/npm
--- a/tests/fixtures/mockbin/npm-fail/npm
+++ b/tests/fixtures/mockbin/npm-fail/npm
@@ -1,5 +1,5 @@
 #!/bin/sh -e
 exitcode=7
-echo 'test: stderr' >&2
-echo "test: the exit code will be $exitcode"
+# echo 'test: stderr' >&2
+# echo "test: the exit code will be $exitcode"
 exit $exitcode
